### ISSUE TITLE
Logical naming error in TCP Echo Client

### ISSUE THREAD

**Issue by vteam27** [okieLoki/NP#1]
We pass the socket address of the server in the `connect()` function rather than the client. 
The port 22000 is the server's port number as defined in the TCP echo server file, the code is logically correct, but the naming of the variable is misleading.

```
    struct sockaddr_in cliaddr;

    bzero(&cliaddr, sizeof(cliaddr));

    cliaddr.sin_family = AF_INET;
    cliaddr.sin_port = htons(22000);
    cliaddr.sin_addr.s_addr = inet_addr("127.0.0.1");

    connect(sockfd, (struct sockaddr *)&cliaddr, sizeof(cliaddr));
```

change it to :

``` 
    struct sockaddr_in servaddr;

    bzero(&servaddr, sizeof(servaddr));

    servaddr.sin_family = AF_INET;
    servaddr.sin_port = htons(22000);
    servaddr.sin_addr.s_addr = inet_addr("127.0.0.1");

    connect(sockfd, (struct sockaddr *)&servaddr, sizeof(servaddr));
```

**Comment by vteam27** [comment]
Similar changes are needed in other client files as well.

**Comment by okieLoki** [comment]
resolved

**Comment by okieLoki** [comment]
> Similar changes are needed in other client files as well.

resolved

**Comment by okieLoki** [comment]
> Similar changes are needed in other client files as well.

Thanks!
Resolved in both the files
