### ISSUE TITLE
Logical error in UDP servers

### ISSUE THREAD

**Issue by vteam27** [okieLoki/NP#2]
As a UDP sever is connection-less, it needs the client's address every time it sends a message to the client. This client address is captured when the server initially receives a message from the client for the first time using `recvfrom(sockfd,buff,sizeof(buff),0,(struct sockaddr *)&cli,&clen);` function, here cli is an uninitialized `struct sockaddr_in` type variable which we pass to capture the client address.

In your programs, you have overwritten the servaddr instead of creating a new client address variable. Since the servaddr variable is never needed again after `bind()`, the program throws no error, but the code is misleading.

```
int main(){

    int sockfd = socket(AF_INET, SOCK_DGRAM, 0);

    struct sockaddr_in servaddr, cli;

    bzero(&servaddr, sizeof(servaddr));

    servaddr.sin_addr.s_addr = htonl(INADDR_ANY);
    servaddr.sin_family = AF_INET;
    servaddr.sin_port = htons(22000);

    bind(sockfd, (struct sockaddr*) &servaddr, sizeof(servaddr));

    char buffer[255];

    int len = sizeof(cli);

    while(1){
        bzero(buffer, 255);

        recvfrom(sockfd, buffer, sizeof(buffer), 0, (struct sockaddr*) &cli, (struct socklen_t*) &len);

        printf("From client %s", buffer);

        char *token = strtok(buffer, " ");

        int sum = 0;

        while(token != NULL){
            sum += atoi(token);
            token = strtok(NULL, " ");
        }

        char sum_str[10];
        snprintf(sum_str, 10, "%d", sum);

        sendto(sockfd, sum_str, sizeof(sum_str), 0, (struct sockaddr*) &cli, len);
    }
```

**Comment by okieLoki** [comment]
> As a UDP sever is connection-less, it needs the client's address every time it sends a message to the client. This client address is captured when the server initially receives a message from the client for the first time using `recvfrom(sockfd,buff,sizeof(buff),0,(struct sockaddr *)&cli,&clen);` function, here cli is an uninitialized `struct sockaddr_in` type variable which we pass to capture the client address.
> 
> In your programs, you have overwritten the servaddr instead of creating a new client address variable. Since the servaddr variable is never needed again after `bind()`, the program throws no error, but the code is misleading.
> 
> ```
> int main(){
> 
>     int sockfd = socket(AF_INET, SOCK_DGRAM, 0);
> 
>     struct sockaddr_in servaddr, cli;
> 
>     bzero(&servaddr, sizeof(servaddr));
> 
>     servaddr.sin_addr.s_addr = htonl(INADDR_ANY);
>     servaddr.sin_family = AF_INET;
>     servaddr.sin_port = htons(22000);
> 
>     bind(sockfd, (struct sockaddr*) &servaddr, sizeof(servaddr));
> 
>     char buffer[255];
> 
>     int len = sizeof(cli);
> 
>     while(1){
>         bzero(buffer, 255);
> 
>         recvfrom(sockfd, buffer, sizeof(buffer), 0, (struct sockaddr*) &cli, (struct socklen_t*) &len);
> 
>         printf("From client %s", buffer);
> 
>         char *token = strtok(buffer, " ");
> 
>         int sum = 0;
> 
>         while(token != NULL){
>             sum += atoi(token);
>             token = strtok(NULL, " ");
>         }
> 
>         char sum_str[10];
>         snprintf(sum_str, 10, "%d", sum);
> 
>         sendto(sockfd, sum_str, sizeof(sum_str), 0, (struct sockaddr*) &cli, len);
>     }
> ```

Thankss again!

fixed it
